# Generated by Django 4.0 on 2022-01-18 13:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Цвет в HEX', image_field=None, max_length=7, samples=None, unique=True, verbose_name='Цвет (HEX)'),
        ),
    ]
