# Generated by Django 4.0 on 2022-01-18 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridients_for_recipe',
            name='amount',
            field=models.IntegerField(default=1, help_text='Количество', validators=[django.core.validators.MinValueValidator(1, 'Количество ингридинетов не может быть меньше 1')], verbose_name='Количество'),
        ),
    ]
